version: "3.8"
networks:
  default:

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    networks:
      - default
    volumes:
      - ./mosquitto/config:/mosquitto/config

  node:
    build: ./receiver
    container_name: node
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - mqtt

  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: node:3000
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_USERNAME: ${NGROK_USERNAME}
      NGROK_PASSWORD: ${NGROK_PASSWORD}
    depends_on:
      - node
    networks:
      - default

  one_shot_node:
    build: ./update-webhook
    container_name: one_shot_node
    environment:
      NGROK_HOST: ngrok
      NGROK_USERNAME: ${NGROK_USERNAME}
      NGROK_PASSWORD: ${NGROK_PASSWORD}
      TOKEN: ${TOKEN}
      SECRET: ${SECRET}
      NONCE: ${NONCE}
    networks:
      - default
    depends_on:
      - ngrok
